import html
from urllib.parse import quote

def render(rows,title="8 Pillars Residential Concrete LeadBot"):
    cards=[]
    for r in rows:
        i=r.get("id");phone=(r.get("phone") or "").replace("-","");email=r.get("email") or "";addr=r.get("project_address") or "";actions=[]
        touch=f'onclick="navigator.sendBeacon(\'/api/leads/{i}/clicked\')"'
        if phone:actions+=[f'<a class="btn" {touch} href="tel:{html.escape(phone)}">Call</a>',f'<a class="btn" {touch} href="sms:{html.escape(phone)}">Text</a>']
        if email:actions.append(f'<a class="btn" {touch} href="mailto:{html.escape(email)}">Email</a>')
        if addr:actions.append(f'<a class="btn" {touch} target="_blank" href="https://www.google.com/maps/search/?api=1&query={quote(addr)}">Map</a>')
        if r.get("source_url"):actions.append(f'<a class="btn" {touch} target="_blank" href="{html.escape(r["source_url"])}">Original post</a>')
        state="Reviewed" if r.get("clicked_at") else f'Untouched • reminders {r.get("reminder_count") or 0}'
        cards.append('<article class="card '+html.escape((r.get("temperature") or "COLD").lower())+'"><div class="score">'+str(r.get("score",0))+' <span>'+html.escape(r.get("temperature") or "")+'</span></div><h2>'+html.escape(r.get("city") or "Unknown")+' — '+html.escape(r.get("scope") or "Residential concrete")+'</h2><p class="state"><b>'+html.escape(state)+'</b></p><p><b>Contactability:</b> '+html.escape(r.get("contactability") or "—")+' &nbsp; <b>Channel:</b> '+html.escape(r.get("contact_channel") or "—")+'</p><p><b>Poster/contact:</b> '+html.escape(r.get("poster_name") or "Not public")+' &nbsp; <b>Neighborhood:</b> '+html.escape(r.get("neighborhood") or "—")+'</p><p><b>Dimensions:</b> '+html.escape(r.get("dimensions") or "—")+' &nbsp; <b>SF:</b> '+html.escape(str(r.get("square_feet") or "—"))+' &nbsp; <b>Urgency:</b> '+html.escape(r.get("urgency") or "—")+'</p><p><b>Phone:</b> '+html.escape(r.get("phone") or "—")+' &nbsp; <b>Email:</b> '+html.escape(r.get("email") or "—")+'</p><p><b>Project address:</b> '+html.escape(r.get("project_address") or "Not published")+'</p><p class="evidence">'+html.escape((r.get("evidence") or r.get("text") or "")[:500])+'</p><div>'+''.join(actions)+'</div></article>')
    css='body{font-family:system-ui,-apple-system,sans-serif;margin:0;background:#111;color:#eee}header{position:sticky;top:0;background:#181818;padding:18px 4vw;border-bottom:1px solid #333}main{max-width:1100px;margin:auto;padding:20px}.card{background:#1d1d1d;border:1px solid #333;border-left:7px solid #777;border-radius:12px;padding:18px;margin:16px 0}.card.hot{border-left-color:#ff4d4d}.card.warm{border-left-color:#ffb84d}.score{font-size:28px;font-weight:800;float:right}.score span{font-size:13px}.btn{display:inline-block;margin:6px 8px 0 0;padding:9px 12px;border-radius:8px;background:#eee;color:#111;text-decoration:none;font-weight:700}.evidence{color:#bbb}.state{color:#ffcf70}'
    return '<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+html.escape(title)+'</title><style>'+css+'</style></head><body><header><h1>'+html.escape(title)+'</h1><p>30-minute capture • 48-hour untouched reminders • duplicate suppression</p></header><main>'+(''.join(cards) if cards else '<p>No qualified leads yet. Run a scan.</p>')+'</main></body></html>'
